---
homework04

1. Read in global gender inequality data

2. Join the global gender inequality index to spatial data of the World, creating a new column of difference in inequality between 2010 and 2019

3.Share it with the World on GitHub
---

## load library

```{r}

library(sf)
library(tidyverse)
library(janitor)
library(here)
library(countrycode)
library(dplyr)

```

## load data

```{r}

data_all <- read_csv(here::here('data/HDR21-22_Composite_indices_complete_time_series.csv')
                     , na='Null')

world_shape <- st_read(here::here('data','World_Countries_Generalized','World_Countries_Generalized.shp'))

```

## select GII data & calculate

```{r}

GIIdata <- data_all %>%
  select(iso3,country,gii_1990:gii_2021) %>%
  mutate(GII_19_10 = gii_2019-gii_2010) %>%
  mutate(diff_19_10 = case_when(GII_19_10>0 ~ "GII has risen",
                                GII_19_10<0 ~ "GII has declined",
                                GII_19_10==0 ~ "GII has not changed")) %>%
  mutate(iso2 = countrycode(iso3,origin = 'iso3c',destination = 'iso2c')) 

missing_value <- is.na(GIIdata$iso2)
GIIdata_clean <- GIIdata[!missing_value,]

```

## join

```{r}

world_shape_new <- world_shape %>%
  left_join(.,GIIdata_clean,by=c("ISO"="iso2"))

```

## mapping

```{r}

```